<?php

/**
 * ColorNames class generator.
 */

function makeColors(string $file)
{
    if (($lines = @file_get_contents($file)) === false) {
        throw new RuntimeException("Couldn't open colors file: " . $file);
    }

    foreach (explode("\n", $lines) as $line) {
        if (!preg_match('/^[ \t]*([0-9]+)[ \t]+([0-9]+)[ \t]+([0-9]+)[ \t]+(.+)$/', $line, $match)) {
            continue;
        }
        [$_, $r, $g, $b, $name] = $match;
        yield $name => fn () => printf('%d, %d, %d', $r, $g, $b);
    }

}

$filename = $argv[1] ?: 'colors.txt';
if (! file_exists($filename)) {
    throw new RuntimeException("File not exist: " . $filename);
}

echo "<?php declare(strict_types=1);\n";

?>

namespace PhpGui;

/**
 * DON'T EDIT THIS CLASS !
 *
 * It was generated by make-color-names.php script.
 */
class ColorNames
{
    public static $color = [
<?php foreach (makeColors($filename) as $name => $rgb): ?>
        '<?= strtolower($name) ?>' => [<?php $rgb() ?>],
<?php endforeach ?>
    ];
}
